language: python

python:
    - "3.4"
    - "3.6"

install:
    - sudo apt install -y gcc g++ shellcheck
    - pip install flake8 cpplint

script:
    - make lint
    - make test

notifications:
    email: false
