language: python

python:
    - "3.4"
    - "3.6"

services:
    - postgresql

install:
    - sudo apt install -y gcc g++
    - pip install flake8 cpplint

before_script:
    - psql -c 'create database uri;' -U postgres

script:
    - make lint
    - make test

notifications:
    email: false
