language: python

python:
    - "3.4"
    - "3.6"

install:
    - sudo apt install -y gcc g++
    - pip install flake8 cpplint

script:
    - flake8
    - cpplint --filter="-legal/copyright" \
        $(find . -regextype egrep -regex '(.+\.c$|.+\.cpp)$')
    - ./run-all.sh

notifications:
    email: false
