#!/bin/bash
#vim:set ft=sh

. _checkers
. _runners

check_tags_file && check_lint || exit 1

run_c_code && (check_solution &&
    echo "C code works" || echo -e "\nC code failed")

run_cpp_code && (check_solution &&
    echo "C++ code works" || echo -e "\nC++ code failed")

run_py_code && (check_solution &&
        echo "Python code works" || echo -e "\nC++ code failed")

run_js_code && (check_solution &&
        echo "Javascript code works" || echo -e "\nC++ code failed")

run_go_code && (check_solution &&
    echo "Golang code works" || echo -e "\nC++ code failed")

run_cl_code && (check_solution &&
    echo "Common Lisp code works" || echo -e "\nC++ code failed")

cleanup
