#!/bin/bash
#vim:set ft=sh

function _can_create_folder {
    not_empty_with_no_folders=1
    correct_depth=1

    if [ -n "$(ls -F | grep '/')" ]; then
        cd "$(ls -F | grep '/' | head -1)"
        if [ -n "$(ls -F | grep '/')" ]; then
            correct_depth=0
        fi
        cd - > /dev/null
    fi

    if [ -z "$(ls -F | grep '/')" -a -n "$(ls -F | grep -v '/')" ]; then
        not_empty_with_no_folders=0
    fi

    if [ $correct_depth == 0 -o $not_empty_with_no_folders == 0 ]; then
        echo
        echo -n "You probably are trying to create the solution folder in the "
        echo "wrong place!!!"
        echo
        echo "You are now here $PWD"
        echo
        return 1
    fi

    return 0
}

if ! _can_create_folder; then
    exit 1
fi

if [ -z $1 ]; then
    echo
    echo "You should inform a problem ID."
    echo
    exit 1
fi

dir=$1
language=${2:-cpp}

if [ -d $dir ]; then
    echo
    echo "Already there is a folder called $dir."
    echo
    exit 1
fi

mkdir $dir && echo "Created $dir."

touch $dir.$language
touch in.txt
touch out.txt
touch tags
touch problem.txt
touch WRONG
