#!/bin/bash
#vim:set ft=sh

TIME=$(which time)
WRITE=0

while [[ $# > 0 ]]; do
    case $1 in
        --write|-w)
            WRITE=1
        ;;
    esac
    shift
done

function compile_program {
    g++ -Wall -lm *.cpp;
}

function run_program {
    $TIME -pao /tmp/$$ ./a.out < in.txt > out.temp
}

function calculate_median {
    lines_count=$(grep 'real' /tmp/$$ | wc -l)
    grep 'real' /tmp/$$ |\
        sed 's/[^0-9.]//g' |\
        head -$(( $lines_count / 2)) |\
        tail -1
}

for i in $(seq 100); do
    compile_program
    run_program
done

if [ $WRITE == 1 ]; then
    calculate_median > .time
else
    calculate_median
fi
