version: '3'

services:
  database-client:
    build:
      context: ../
      dockerfile: $DOCKER_PATH/sql.Dockerfile
    environment:
      DOCKER_PATH: $DOCKER_PATH
      FOLDERS: $FOLDERS
      POSTGRES_DB: beecrowd
      POSTGRES_USER: beecrowd
    volumes:
      - ..:/code
    depends_on:
      - database-server
    user: $USER
  database-server:
    image: postgres:9.4.19
    environment:
      POSTGRES_DB: beecrowd
      POSTGRES_USER: beecrowd
      POSTGRES_PASSWORD: beecrowd
    volumes:
        - /tmp/db:/var/lib/postgresql/data
