version: '3'

services:
  database-client:
    build:
      context: ../
      dockerfile: .docker/sql.Dockerfile
    environment:
      PROBLEM: $PROBLEM
      POSTGRES_DB: beecrowd
      POSTGRES_USER: beecrowd
    volumes:
      - ..:/code
    depends_on:
      - database-server
    user: $USER
  database-server:
    image: postgres:9.4.19
    environment:
      POSTGRES_DB: beecrowd
      POSTGRES_USER: beecrowd
    volumes:
        - /tmp/db:/var/lib/postgresql/data
