#!/bin/bash
#vim:set ft=sh

set -e

paths=$(find . -name 'problem.txt')

for path in $paths; do
    path=$(sed 's/problem.txt//g' <<< "$path")
    cd $path
    pwd
    if [ ! -f WRONG ]; then
        marathon
    fi
    cd - > /dev/null
done
