name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clear up some space on runner
        run: |
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          sudo sudo apt update
          sudo apt-get remove -y '^aspnetcore-.*'
          sudo apt-get remove -y '^azure-.*'
          sudo apt-get remove -y '^clang-.*'
          sudo apt-get remove -y '^cpp-.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^gfortran-.*'
          sudo apt-get remove -y '^google-.*'
          sudo apt-get remove -y '^libclang.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y '^microsoft-.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mono-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y '^php.*'
          sudo apt-get remove -y '^postgresql-.*'
          sudo apt-get remove -y '^temurin-.*'
          sudo apt-get remove -y firefox powershell
          sudo apt-get autoremove -y
          sudo apt-get clean
          rm -rf /usr/share/dotnet/
          df -h
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if tags are correct
        run: |
          make check-tags
      - name: Run solutions
        run: |
          make run
