name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run lint
        run: |
          make lint

      - name: run solutions
        run: |
          make run
